#!/bin/sh
#$ -S /bin/bash
#$ -cwd
#$ -j y
#$ -l lr=1
#$ -l mem=6000
#$ -v PATH
#$ -M fj228
#$ -m eas

# load the experiment cofiguration
source $1

# expand the paths
source ./settings.path

mkdir $TBEDP_RESULTS_DIR

echo $1 > $TBEDP_RESULTS_DIR/settings
echo `date` >> $TBEDP_RESULTS_DIR/settings
env | grep TBEDP | sort >> $TBEDP_RESULTS_DIR/settings

date
time ./src/tbedp-trainer.py -v $TBEDP_OPTS \
  --tmpData=$TBEDP_RESULTS_DIR \
  --trainData=$TBEDP_TRAIN_DATA \
  --outPickle=$TBEDP_OUT_PICKLE \
  --outDecoderPickle=$TBEDP_OUT_DECODER_PICKLE \
  --outRules=$TBEDP_OUT_RULES \
  --outDict=$TBEDP_OUT_DICT \
  --trgCond="$TBEDP_TRG_COND" \
  --db=$TBEDP_DB
  
./src/tbedp-decoder.py -v $TBEDP_OPTS \
  --testData=$TBEDP_TEST_DATA_SEM \
  --inPickle=$TBEDP_OUT_DECODER_PICKLE \
  --outSem=$TBEDP_OUT_SEM_HYP \
  --inDict=$TBEDP_OUT_DICT
#  --db=$TBEDP_DB

./src/tbedp-decoder.py -v $TBEDP_OPTS \
  --testData=$TBEDP_TEST_DATA_ASR \
  --inPickle=$TBEDP_OUT_DECODER_PICKLE \
  --outSem=$TBEDP_OUT_ASR_HYP \
  --inDict=$TBEDP_OUT_DICT
#  --db=$TBEDP_DB

./src/tbedp-decoder.py -v $TBEDP_OPTS \
  --testData=$TBEDP_DEV_DATA_SEM \
  --inPickle=$TBEDP_OUT_DECODER_PICKLE \
  --outSem=$TBEDP_OUT_DEV_SEM_HYP \
  --inDict=$TBEDP_OUT_DICT
#  --db=$TBEDP_DB

./src/tbedp-decoder.py -v $TBEDP_OPTS \
  --testData=$TBEDP_DEV_DATA_ASR \
  --inPickle=$TBEDP_OUT_DECODER_PICKLE \
  --outSem=$TBEDP_OUT_DEV_ASR_HYP \
  --inDict=$TBEDP_OUT_DICT 
#  --db=$TBEDP_DB

./src/tbedp-decoder.py -v $TBEDP_OPTS \
  --testData=$TBEDP_TRAIN_DATA \
  --inPickle=$TBEDP_OUT_DECODER_PICKLE \
  --outSem=$TBEDP_OUT_TRN_HYP \
  --inDict=$TBEDP_OUT_DICT
#  --db=$TBEDP_DB
  
./bin/cuedSemScore.pl $TBEDP_OUT_SEM_HYP $TBEDP_TEST_DATA_SEM
./bin/cuedSemScore.pl $TBEDP_OUT_SEM_HYP $TBEDP_TEST_DATA_SEM > $TBEDP_OUT_SEM_HYP.rslt
./bin/cuedSemScore.pl $TBEDP_OUT_ASR_HYP $TBEDP_TEST_DATA_ASR > $TBEDP_OUT_ASR_HYP.rslt

./bin/cuedSemScore.pl $TBEDP_OUT_DEV_SEM_HYP $TBEDP_DEV_DATA_SEM > $TBEDP_OUT_DEV_SEM_HYP.rslt
./bin/cuedSemScore.pl $TBEDP_OUT_DEV_ASR_HYP $TBEDP_DEV_DATA_ASR > $TBEDP_OUT_DEV_ASR_HYP.rslt

./bin/cuedSemScore.pl $TBEDP_OUT_TRN_HYP $TBEDP_TRAIN_DATA > $TBEDP_OUT_TRN_HYP.rslt

./src/analyzeHyp.py --hypData=$TBEDP_OUT_DEV_SEM_HYP --refData=$TBEDP_DEV_DATA_SEM > $TBEDP_OUT_DEV_SEM_HYP.anlz
./src/analyzeHyp.py --hypData=$TBEDP_OUT_DEV_ASR_HYP --refData=$TBEDP_DEV_DATA_ASR > $TBEDP_OUT_DEV_ASR_HYP.anlz
./src/analyzeHyp.py --hypData=$TBEDP_OUT_TRN_HYP --refData=$TBEDP_TRAIN_DATA > $TBEDP_OUT_TRN_HYP.anlz

OLD_PWD=`pwd`
cd $TBEDP_RESULTS_DIR
grph $TBEDP_OPTS 
cd $OLD_PWD

date

echo `date` >> $TBEDP_RESULTS_DIR/settings
