#!/bin/sh

source $1

export TBEDP_EXPERIMENT_NAME=`date +%Y-%m-%d-%H.%M`
export TBEDP_RESULTS_DIR=./results/$TBEDP_EXPERIMENT_NAME
export TBEDP_TRAIN_DATA=./data/$TBEDP_DATA_FILE
export TBEDP_OUT_PICKLE=$TBEDP_RESULTS_DIR/$TBEDP_DATA_FILE.pickle
export TBEDP_OUT_RULES=$TBEDP_RESULTS_DIR/$TBEDP_DATA_FILE.rules

mkdir $TBEDP_RESULTS_DIR

date
time ./src/tbedp-trainer.py -v \
  --tmpData=$TBEDP_RESULTS_DIR \
  --trainData=$TBEDP_TRAIN_DATA \
  --outPickle=$TBEDP_OUT_PICKLE \
  --outRules=$TBEDP_OUT_RULES \
  --nGrams=$TBEDP_NGRAMS \
  --tplGrams=$TBEDP_TPLGRAMS
date

echo $1 > $TBEDP_RESULTS_DIR/settings
env | grep TBEDP | sort >> $TBEDP_RESULTS_DIR/settings